name: abm
channels:
- conda-forge
- defaults
dependencies:
- jupyter ~=1.0
- mesa ~=0.8.8
- statsmodels ~=0.12
- salib ~=1.3
- pandas ~=1.1
- numpy ~=1.19
- matplotlib ~=3.3
- pip
- pip:
    - axelrod ~=4.10
    - ipynb ~=0.5
